(TeX-add-style-hook "thuthesis"
 (lambda ()
    (LaTeX-add-index-entries
     "commands!#1@\\texttt{\\bs#1}"
     "#1@\\texttt{\\hspace*{-1.2ex}\\bs #1}"
     "packages!#1@\\textsf{#1}"
     "#1@\\textsf{#1}"
     "environments!\\texttt{#1}"
     "#1@\\texttt{#1}"
     "#1"
     "#1\\actualchar\\textbf{#1}")
    (LaTeX-add-environments
     "description"
     "enumerate"
     "itemize"
     "assumption"
     "definition"
     "proposition"
     "lemma"
     "theorem"
     "axiom"
     "corollary"
     "exercise"
     "example"
     "remark"
     "problem"
     "conjecture"
     "cabstract"
     "eabstract"
     "denotation"
     "ack"
     "resume")
    (TeX-add-symbols
     '("shuji" ["argument"] 0)
     '("makecover" ["argument"] 0)
     '("cdepartment" ["argument"] 1)
     '("CJKtoday" ["argument"] 0)
     '("MakePerPage" ["argument"] 1)
     '("wi" 1)
     '("ei" 1)
     '("pai" 1)
     '("ci" 1)
     '("cih" 1)
     '("resumeitem" 1)
     '("makescanversion" 1)
     '("getcmlength" 1)
     "thu"
     "listequationname"
     "equationname"
     "CJKprepartname"
     "CJKpartname"
     "CJKthepart"
     "CJKprechaptername"
     "CJKchaptername"
     "CJKthechapter"
     "cabstractname"
     "eabstractname"
     "declarescanname"
     "listofequations"
     "onlinecite"
     "bs"
     "pozhehao"
     "version"
     "cleardoublepage"
     "footnoterule"
     "hlinewd"
     "caffil"
     "csubject"
     "eaffil"
     "esubject"
     "secondlinelength"
     "firstlinelength"
     "oldnumberline"
     "numberline"
     "equcaption"
     "thudot"
     "thumasterbib"
     "thuphdbib"
     "DescribeOption"
     "SpecialOptionIndex"
     "myentry"
     "tableofcontents"
     "DescribeMacro"
     "PrintDescribeMacro"
     "sectionmark"
     "subsectionmark"
     "subsubsectionmark")
    (TeX-run-style-hooks
     "indentfirst"
     "url"
     "winfonts"
     "ctex"
     "nofonts"
     "xcolor"
     "fancyvrb"
     "fancybox"
     "pdfpages"
     "natbib"
     "numbers"
     "super"
     "sort&compress"
     "booktabs"
     "longtable"
     "array"
     "ntheorem"
     "thmmarks"
     "hyperref"
     "arial"
     "CJKspace"
     "footmisc"
     "bottom"
     "paralist"
     "neverdecrease"
     "subcaption"
     "graphicx"
     "txfonts"
     "amsmath"
     "calc"
     "ifthen"
     "ifxetex"
     "ctexbook10"
     "ctexbook"
     "cs4size"
     "a4paper"
     "openany"
     "UTF8"
     "dtx-style"
     "latex2e"
     "ltxdoc10"
     "ltxdoc"
     "10pt"
     "fontname")))

